AUTH_URL: "https://idp.trusona.com/authorizations/openid"
TOKEN_URL: "https://idp.trusona.com/openid/token"
USERINFO_URL: "https://idp.trusona.com/openid/userinfo"
PIZZA_SERVER: "http://pizza_server:3000/"
SECRET_KEY: "tlXmvITyUQFlZQwAGxK9rMWaHKbXzmF2cZcmfYOPs1gIh4zBivpJdB6HPujyHKCW"
DEBUG: True
AUTH_ENABLED: False
