version: '2'
services:
  db:
    image: postgres
  pizza_server:
    image: trusona/pizza-server
    build: pizza_server
    depends_on:
      - db
  pizza_client:
    build: .
    depends_on:
      - pizza_server
  haproxy:
    build:
      context: pizza_client/extra
      dockerfile: Dockerfile-haproxy
    ports:
      - "8080:80"
    depends_on:
      - pizza_client
