version: '2'
services:
  db:
    image: postgres
  web:
    image: trusona/pizza-server
    build: pizza_server
    depends_on:
      - db
  web2:
    build: .
    depends_on:
      - web
  haproxy:
    build:
      context: .
      dockerfile: Dockerfile-haproxy
    ports:
      - "8080:80"
    depends_on:
      - web2
